#!/usr/bin/env python

import argparse
import pydoc
import sys
import {modulename}

sys.path.append("{pyfs_module_path}")

from pyfs.scriptsupport import exit_with, run_for_input


def parse_args():
    parser = argparse.ArgumentParser(description=pydoc.render_doc(
        {modulename}.{thingname}))
    parser.add_argument("funcargs", nargs="*")
    return parser.parse_args()


def main():
    exit_with(run_for_input({modulename}.{thingname}, parse_args().funcargs))


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.stdout.flush()
